version: '3'

services:
  app:
    image: 'spring-qa-service:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - pg
    environment:
      - TZ=Europe/Warsaw
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - JWT_CONFIG_SECRET=DOCKER
    ports:
      - 8080:8080
  pg:
    image: 'postgres:latest'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432